export enum LanguageCode {
  Arabic = "ar",
  Bangla = "bn",
  Bulgarian = "bg",
  Catalan = "ca",
  ChineseSimplified = "zh-Hans",
  ChineseTraditional = "zh-Hant",
  Croatian = "hr",
  Czech = "cs",
  Danish = "da",
  Dutch = "nl",
  English = "en",
  Estonian = "et",
  Filipino = "fil",
  Finnish = "fi",
  French = "fr",
  FrenchCanada = "fr-ca",
  German = "de",
  Greek = "el",
  Gujarati = "gu",
  Hebrew = "he",
  Hindi = "hi",
  Hungarian = "hu",
  Icelandic = "is",
  Indonesian = "id",
  Italian = "it",
  Japanese = "ja",
  Kannada = "kn",
  Korean = "ko",
  Latvian = "lv",
  Lithuanian = "lt",
  Malayalam = "ml",
  Marathi = "mr",
  NorwegianBokmal = "nb",
  Persian = "fa",
  Polish = "pl",
  PortugueseBrazil = "pt",
  PortuguesePortugal = "pt-pt",
  Punjabi = "pa",
  Romanian = "ro",
  Russian = "ru",
  SerbianCyrillic = "sr-Cyrl",
  Slovak = "sk",
  Slovenian = "sl",
  Spanish = "es",
  SwahiliLatin = "sw",
  Swedish = "sv",
  Tamil = "ta",
  Telugu = "te",
  Thai = "th",
  Turkish = "tr",
  Ukrainian = "uk",
  Urdu = "ur",
  Vietnamese = "vi",
}

export const languageCodeValues = Object.values(LanguageCode) as [
  LanguageCode,
  ...LanguageCode[],
];

export const languageCodeToName: Record<LanguageCode, string> = {
  [LanguageCode.Arabic]: "Arabic",
  [LanguageCode.Bangla]: "Bangla",
  [LanguageCode.Bulgarian]: "Bulgarian",
  [LanguageCode.Catalan]: "Catalan",
  [LanguageCode.ChineseSimplified]: "Chinese Simplified",
  [LanguageCode.ChineseTraditional]: "Chinese Traditional",
  [LanguageCode.Croatian]: "Croatian",
  [LanguageCode.Czech]: "Czech",
  [LanguageCode.Danish]: "Danish",
  [LanguageCode.Dutch]: "Dutch",
  [LanguageCode.English]: "English",
  [LanguageCode.Estonian]: "Estonian",
  [LanguageCode.Filipino]: "Filipino",
  [LanguageCode.Finnish]: "Finnish",
  [LanguageCode.French]: "French",
  [LanguageCode.FrenchCanada]: "French (Canada)",
  [LanguageCode.German]: "German",
  [LanguageCode.Greek]: "Greek",
  [LanguageCode.Gujarati]: "Gujarati",
  [LanguageCode.Hebrew]: "Hebrew",
  [LanguageCode.Hindi]: "Hindi",
  [LanguageCode.Hungarian]: "Hungarian",
  [LanguageCode.Icelandic]: "Icelandic",
  [LanguageCode.Indonesian]: "Indonesian",
  [LanguageCode.Italian]: "Italian",
  [LanguageCode.Japanese]: "Japanese",
  [LanguageCode.Kannada]: "Kannada",
  [LanguageCode.Korean]: "Korean",
  [LanguageCode.Latvian]: "Latvian",
  [LanguageCode.Lithuanian]: "Lithuanian",
  [LanguageCode.Malayalam]: "Malayalam",
  [LanguageCode.Marathi]: "Marathi",
  [LanguageCode.NorwegianBokmal]: "Norwegian Bokmål",
  [LanguageCode.Persian]: "Persian",
  [LanguageCode.Polish]: "Polish",
  [LanguageCode.PortugueseBrazil]: "Portuguese (Brazil)",
  [LanguageCode.PortuguesePortugal]: "Portuguese (Portugal)",
  [LanguageCode.Punjabi]: "Punjabi",
  [LanguageCode.Romanian]: "Romanian",
  [LanguageCode.Russian]: "Russian",
  [LanguageCode.SerbianCyrillic]: "Serbian (Cyrillic)",
  [LanguageCode.Slovak]: "Slovak",
  [LanguageCode.Slovenian]: "Slovenian",
  [LanguageCode.Spanish]: "Spanish",
  [LanguageCode.SwahiliLatin]: "Swahili (Latin)",
  [LanguageCode.Swedish]: "Swedish",
  [LanguageCode.Tamil]: "Tamil",
  [LanguageCode.Telugu]: "Telugu",
  [LanguageCode.Thai]: "Thai",
  [LanguageCode.Turkish]: "Turkish",
  [LanguageCode.Ukrainian]: "Ukrainian",
  [LanguageCode.Urdu]: "Urdu",
  [LanguageCode.Vietnamese]: "Vietnamese",
};
