import type { videos } from "@/server/db/schema";

export type Video = typeof videos.$inferSelect;

type SampleVideo = Pick<
  Video,
  | "id"
  | "title"
  | "createdById"
  | "createdAt"
  | "sourceBlob"
  | "completedBlob"
  | "status"
  | "sourceLanguage"
  | "destLanguage"
>;

export const sampleVideos: SampleVideo[] = [
  {
    id: "video-1",
    title: "Sample video",
    createdById: "user-1",
    createdAt: new Date(),
    sourceBlob: "placeholder-blob",
    completedBlob: null,
    status: "done",
    sourceLanguage: "en",
    destLanguage: "es",
  },
  {
    id: "video-2",
    title: "Quarterly product update",
    createdById: "user-2",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    sourceBlob: "placeholder-blob",
    completedBlob: null,
    status: "processing",
    sourceLanguage: "de",
    destLanguage: "en",
  },
  {
    id: "video-3",
    title: "Customer testimonial",
    createdById: "user-3",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
    sourceBlob: "placeholder-blob",
    completedBlob: "completed-blob-3",
    status: "done",
    sourceLanguage: "fr",
    destLanguage: "pt",
  },
  {
    id: "video-4",
    title: "Conference keynote",
    createdById: "user-4",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    sourceBlob: "placeholder-blob",
    completedBlob: null,
    status: "queued",
    sourceLanguage: "ja",
    destLanguage: "en",
  },
  {
    id: "video-5",
    title: "Team onboarding",
    createdById: "user-5",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36),
    sourceBlob: "placeholder-blob",
    completedBlob: null,
    status: "failed",
    sourceLanguage: "es",
    destLanguage: "fr",
  },
  {
    id: "video-6",
    title: "Marketing teaser",
    createdById: "user-6",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    sourceBlob: "placeholder-blob",
    completedBlob: "completed-blob-6",
    status: "done",
    sourceLanguage: "it",
    destLanguage: "en",
  },
  {
    id: "video-7",
    title: "Support tutorial",
    createdById: "user-7",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 60),
    sourceBlob: "placeholder-blob",
    completedBlob: null,
    status: "processing",
    sourceLanguage: "en",
    destLanguage: "de",
  },
  {
    id: "video-8",
    title: "Product walkthrough",
    createdById: "user-8",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
    sourceBlob: "placeholder-blob",
    completedBlob: null,
    status: "queued",
    sourceLanguage: "ko",
    destLanguage: "en",
  },
  {
    id: "video-9",
    title: "Engineering demo",
    createdById: "user-9",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 84),
    sourceBlob: "placeholder-blob",
    completedBlob: "completed-blob-9",
    status: "done",
    sourceLanguage: "pt",
    destLanguage: "es",
  },
  {
    id: "video-10",
    title: "Sales pitch",
    createdById: "user-10",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96),
    sourceBlob: "placeholder-blob",
    completedBlob: null,
    status: "failed",
    sourceLanguage: "ru",
    destLanguage: "en",
  },
  {
    id: "video-11",
    title: "Customer success story",
    createdById: "user-11",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 108),
    sourceBlob: "placeholder-blob",
    completedBlob: "completed-blob-11",
    status: "done",
    sourceLanguage: "de",
    destLanguage: "en",
  },
  {
    id: "video-12",
    title: "Internal training",
    createdById: "user-12",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120),
    sourceBlob: "placeholder-blob",
    completedBlob: null,
    status: "processing",
    sourceLanguage: "en",
    destLanguage: "de",
  },
  {
    id: "video-13",
    title: "Partner announcement",
    createdById: "user-13",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 132),
    sourceBlob: "placeholder-blob",
    completedBlob: null,
    status: "queued",
    sourceLanguage: "ru",
    destLanguage: "de",
  },
  {
    id: "video-14",
    title: "Localization update",
    createdById: "user-14",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 144),
    sourceBlob: "placeholder-blob",
    completedBlob: "completed-blob-14",
    status: "done",
    sourceLanguage: "fr",
    destLanguage: "en",
  },
  {
    id: "video-15",
    title: "Feature spotlight",
    createdById: "user-15",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 156),
    sourceBlob: "placeholder-blob",
    completedBlob: null,
    status: "processing",
    sourceLanguage: "es",
    destLanguage: "fr",
  },
];
