import type { videos } from "@/server/db/schema";
import { LanguageName } from "@/lib/languages";

export type Video = typeof videos.$inferSelect;

export const sampleVideos: Video[] = [
	{
		id: "video-1",
		title: "Sample video",
		createdById: "user-1",
		createdAt: new Date(),
		blob: "placeholder-blob",
		status: "ready",
		sourceLanguage: LanguageName.English,
		destLanguage: LanguageName.Spanish,
	},
	{
		id: "video-2",
		title: "Quarterly product update",
		createdById: "user-2",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
		blob: "placeholder-blob",
		status: "processing",
		sourceLanguage: LanguageName.German,
		destLanguage: LanguageName.English,
	},
	{
		id: "video-3",
		title: "Customer testimonial",
		createdById: "user-3",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
		blob: "placeholder-blob",
		status: "ready",
		sourceLanguage: LanguageName.French,
		destLanguage: LanguageName.Portuguese,
	},
	{
		id: "video-4",
		title: "Conference keynote",
		createdById: "user-4",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
		blob: "placeholder-blob",
		status: "queued",
		sourceLanguage: LanguageName.Japanese,
		destLanguage: LanguageName.English,
	},
	{
		id: "video-5",
		title: "Team onboarding",
		createdById: "user-5",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36),
		blob: "placeholder-blob",
		status: "failed",
		sourceLanguage: LanguageName.Spanish,
		destLanguage: LanguageName.French,
	},
	{
		id: "video-6",
		title: "Marketing teaser",
		createdById: "user-6",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
		blob: "placeholder-blob",
		status: "ready",
		sourceLanguage: LanguageName.Italian,
		destLanguage: LanguageName.English,
	},
	{
		id: "video-7",
		title: "Support tutorial",
		createdById: "user-7",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 60),
		blob: "placeholder-blob",
		status: "processing",
		sourceLanguage: LanguageName.English,
		destLanguage: LanguageName.German,
	},
	{
		id: "video-8",
		title: "Product walkthrough",
		createdById: "user-8",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
		blob: "placeholder-blob",
		status: "queued",
		sourceLanguage: LanguageName.Korean,
		destLanguage: LanguageName.English,
	},
	{
		id: "video-9",
		title: "Engineering demo",
		createdById: "user-9",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 84),
		blob: "placeholder-blob",
		status: "ready",
		sourceLanguage: LanguageName.Portuguese,
		destLanguage: LanguageName.Spanish,
	},
	{
		id: "video-10",
		title: "Sales pitch",
		createdById: "user-10",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96),
		blob: "placeholder-blob",
		status: "failed",
		sourceLanguage: LanguageName.Russian,
		destLanguage: LanguageName.English,
	},
	{
		id: "video-11",
		title: "Customer success story",
		createdById: "user-11",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 108),
		blob: "placeholder-blob",
		status: "ready",
		sourceLanguage: LanguageName.German,
		destLanguage: LanguageName.English,
	},
	{
		id: "video-12",
		title: "Internal training",
		createdById: "user-12",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120),
		blob: "placeholder-blob",
		status: "processing",
		sourceLanguage: LanguageName.English,
		destLanguage: LanguageName.German,
	},
	{
		id: "video-13",
		title: "Partner announcement",
		createdById: "user-13",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 132),
		blob: "placeholder-blob",
		status: "queued",
		sourceLanguage: LanguageName.Russian,
		destLanguage: LanguageName.German,
	},
	{
		id: "video-14",
		title: "Localization update",
		createdById: "user-14",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 144),
		blob: "placeholder-blob",
		status: "ready",
		sourceLanguage: LanguageName.French,
		destLanguage: LanguageName.English,
	},
	{
		id: "video-15",
		title: "Feature spotlight",
		createdById: "user-15",
		createdAt: new Date(Date.now() - 1000 * 60 * 60 * 156),
		blob: "placeholder-blob",
		status: "processing",
		sourceLanguage: LanguageName.Spanish,
		destLanguage: LanguageName.French,
	},
];
